//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCandyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int Id { get; set; }
        public string displayName { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
