//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCandyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int Id { get; set; }
        public string cartGUID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
